all:
  hosts:
    node1:
      ansible_host: 172.10.30.31
      ip: 172.10.30.31
      access_ip: 172.10.30.31
    node2:
      ansible_host: 172.10.30.32
      ip: 172.10.30.32
      access_ip: 172.10.30.32
    node3:
      ansible_host: 172.10.30.33
      ip: 172.10.30.33
      access_ip: 172.10.30.33
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
